apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: raniket/docker-first:part1
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
  labels:
    app: ndoeapp-svc
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 30001
  selector:
    app: nodeapp
